[package]
name = "aiogguf"
version = "0.1.0"
authors = ["Dex"]
edition = "2024"
description = "Pure Rust GGUF format parser library for AIOxide"
license = "MIT OR Apache-2.0"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0"

[dev-dependencies]
